spring:
  application:
    name: school-management
  datasource:
    url: jdbc:mysql://localhost:3306/school?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
  secretKey: 2D4A614E645267556B58703273357638792F423F4428472B4B6250655368566D
  expirationHours: 24