spring:
  application:
    name: school-management
  datasource:
    url: jdbc:mysql://localhost/school
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: create